spring:
  data:
    mongodb:
      port: 27017
      database: library

mongock:
  runner-type: "InitializingBean"
  migration-scan-package:
    - ru.vavtech.hw8.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local